export const LIMITS = {
  MEDIA_CACHE_EXPIRATION_DAYS: Number(process.env.MEDIA_CACHE_EXPIRATION_DAYS) || 30,
  USER_MEDIA_SEARCH_LIMIT: Number(process.env.USER_MEDIA_SEARCH_LIMIT) || 100,
  USER_GENERAL_REQUEST_LIMIT: Number(process.env.USER_GENERAL_REQUEST_LIMIT) || 1000,
};
